make run_all:
	g++ main.cpp -o exe
	./exe < in/a_example.txt > out/a.out 2> out/a.score
	./exe < in/b_lovely_landscapes.txt > out/b.out 2> out/b.score
	./exe < in/c_memorable_moments.txt > out/c.out 2> out/c.score
	./exe < in/d_pet_pictures.txt > out/d.out 2> out/d.score
	./exe < in/e_shiny_selfies.txt > out/e.out 2> out/e.score
	rm exe

make run_all2:
	g++ main2.cpp -o exe
	./exe < in/a_example.txt > out2/a.out 2> out2/a.score
	./exe < in/b_lovely_landscapes.txt > out2/b.out 2> out2/b.score
	./exe < in/c_memorable_moments.txt > out2/c.out 2> out2/c.score
	./exe < in/d_pet_pictures.txt > out2/d.out 2> out2/d.score
	./exe < in/e_shiny_selfies.txt > out2/e.out 2> out2/e.score
	rm exe
